### ISSUE TITLE
graph/iterator: segfault in graph/iterator.(*mapIter).next

### ISSUE THREAD

**Issue by sbinet** [gonum/gonum#1728]
with latest `go-tip`:
```
$> go version
go version devel go1.18-534dfb2aeb Tue Sep 28 03:21:58 2021 +0000 linux/amd64
```

I get the following segfault when running tests in `graph` (at 06c2c527):

```
FAIL	gonum.org/v1/gonum/graph/topo	0.649s
unexpected fault address 0x8000103
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8000103 pc=0x40efaa]

goroutine 5 [running]:
runtime.throw({0x52c95f, 0x203000})
	/home/binet/sdk/go/src/runtime/panic.go:965 +0x71 fp=0xc000fdeaf8 sp=0xc000fdeac8 pc=0x4343d1
runtime.sigpanic()
	/home/binet/sdk/go/src/runtime/signal_unix.go:803 +0x305 fp=0xc000fdeb48 sp=0xc000fdeaf8 pc=0x448c05
runtime.mapiternext(0xc0001045c0)
	/home/binet/sdk/go/src/runtime/map.go:901 +0x18a fp=0xc000fdebb8 sp=0xc000fdeb48 pc=0x40efaa
runtime.mapiterinit(0x51f760, 0x1, 0xc000fdec40)
	/home/binet/sdk/go/src/runtime/map.go:849 +0x229 fp=0xc000fdebd8 sp=0xc000fdebb8 pc=0x40edc9
reflect.mapiterinit(0x40d067, 0x0, 0xc000fdec40)
	/home/binet/sdk/go/src/runtime/map.go:1361 +0x19 fp=0xc000fdec00 sp=0xc000fdebd8 pc=0x45df99
gonum.org/v1/gonum/graph/iterator.(*mapIter).next(0xc0001045d0)
	/home/binet/work/gonum/src/gonum.org/v1/gonum/graph/iterator/map.go:125 +0x5e fp=0xc000fdec20 sp=0xc000fdec00 pc=0x4f247e
gonum.org/v1/gonum/graph/iterator.(*NodesByEdge).Next(0xc000523200)
	/home/binet/work/gonum/src/gonum.org/v1/gonum/graph/iterator/nodes_map.go:149 +0x37 fp=0xc000fdec50 sp=0xc000fdec20 pc=0x4f2657
gonum.org/v1/gonum/graph/traverse.(*BreadthFirst).Walk(0xc000fdee70, {0x559d08, 0xc00053c1e0}, {0x557fe0, 0x600148}, 0xc000fdee08)
	/home/binet/work/gonum/src/gonum.org/v1/gonum/graph/traverse/traverse.go:72 +0x591 fp=0xc000fded18 sp=0xc000fdec50 pc=0x4f4db1
gonum.org/v1/gonum/graph/traverse.TestBreadthFirst(0xc0010a9a00)
	/home/binet/work/gonum/src/gonum.org/v1/gonum/graph/traverse/traverse_test.go:161 +0x299 fp=0xc000fdef70 sp=0xc000fded18 pc=0x4f5e39
testing.tRunner(0xc0010a9a00, 0x537660)
	/home/binet/sdk/go/src/testing/testing.go:1389 +0x102 fp=0xc000fdefc0 sp=0xc000fdef70 pc=0x4b67a2
testing.(*T).Run.func1()
	/home/binet/sdk/go/src/testing/testing.go:1436 +0x2a fp=0xc000fdefe0 sp=0xc000fdefc0 pc=0x4b766a
runtime.goexit()
	/home/binet/sdk/go/src/runtime/asm_amd64.s:1446 +0x1 fp=0xc000fdefe8 sp=0xc000fdefe0 pc=0x463021
created by testing.(*T).Run
	/home/binet/sdk/go/src/testing/testing.go:1436 +0x35f

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0010a9860, {0x52ebe8, 0x4b6505}, 0x537660)
	/home/binet/sdk/go/src/testing/testing.go:1437 +0x37a
testing.runTests.func1(0xc0010a9860)
	/home/binet/sdk/go/src/testing/testing.go:1777 +0x6e
testing.tRunner(0xc0010a9860, 0xc00008dcd8)
	/home/binet/sdk/go/src/testing/testing.go:1389 +0x102
testing.runTests(0xc000128000, {0x61b180, 0x3, 0x3}, {0x7f15fac64108, 0x0, 0x620300})
	/home/binet/sdk/go/src/testing/testing.go:1775 +0x43f
testing.(*M).Run(0xc000128000)
	/home/binet/sdk/go/src/testing/testing.go:1663 +0x5d9
main.main()
	_testmain.go:75 +0x1aa
FAIL	gonum.org/v1/gonum/graph/traverse	0.319s
```

not sure whether that's a problem in `Gonum` or with `Go`.

**Comment by kortschak** [comment]
I had a change ready for this. Please try it out.
