### ISSUE TITLE
gonum/graph: Segfault with Go 1.18 rc1 during tests

### ISSUE THREAD

**Issue by eclipseo** [gonum/gonum#1775]
Env: Fedora Rawhide, Go 1.18rc1 on x86_64, i686

I'm running the tests during build and encountering the following segfault:

```
gonum.org/v1/gonum/graph
unexpected fault address 0x7040104
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7040104 pc=0x55a20b4c10ea]

goroutine 6 [running]:
runtime.throw({0x55a20b5c2413?, 0x203000?})
        /usr/lib/golang/src/runtime/panic.go:992 +0x71 fp=0xc00005a550 sp=0xc00005a520 pc=0x55a20b4e6411
runtime.sigpanic()
        /usr/lib/golang/src/runtime/signal_unix.go:809 +0x305 fp=0xc00005a5a0 sp=0xc00005a550 pc=0x55a20b4fac65
runtime.mapiternext(0xc00006e6e0)
        /usr/lib/golang/src/runtime/map.go:913 +0x18a fp=0xc00005a610 sp=0xc00005a5a0 pc=0x55a20b4c10ea
runtime.mapiterinit(0x28?, 0x55a20b6588a0?, 0x1?)
        /usr/lib/golang/src/runtime/map.go:861 +0x228 fp=0xc00005a630 sp=0xc00005a610 pc=0x55a20b4c0f08
reflect.mapiterinit(0x515?, 0x55a20b56a0e0?, 0xc00005a688?)
        /usr/lib/golang/src/runtime/map.go:1373 +0x19 fp=0xc00005a658 sp=0xc00005a630 pc=0x55a20b5104b9
gonum.org/v1/gonum/graph/iterator.(*mapIter).next(0xc00006e6f0)
        /builddir/build/BUILD/gonum-0.9.3/_build/src/gonum.org/v1/gonum/graph/iterator/map.go:89 +0x5e fp=0xc00005a678 sp=0xc00005a658 pc=0x55a20b5a9c9e
gonum.org/v1/gonum/graph/iterator.(*Nodes).Next(0xc0003bba40)
        /builddir/build/BUILD/gonum-0.9.3/_build/src/gonum.org/v1/gonum/graph/iterator/nodes_map.go:40 +0x36 fp=0xc00005a698 sp=0xc00005a678 pc=0x55a20b5aa156
gonum.org/v1/gonum/graph_test.TestComplement(0xc0003a2ea0)
        /builddir/build/BUILD/gonum-0.9.3/_build/src/gonum.org/v1/gonum/graph/complement_test.go:36 +0x19a fp=0xc00005a770 sp=0xc00005a698 pc=0x55a20b5b449a
testing.tRunner(0xc0003a2ea0, 0x55a20b6686e8)
        /usr/lib/golang/src/testing/testing.go:1440 +0x102 fp=0xc00005a7c0 sp=0xc00005a770 pc=0x55a20b56a1e2
testing.(*T).Run.func1()
        /usr/lib/golang/src/testing/testing.go:1487 +0x2a fp=0xc00005a7e0 sp=0xc00005a7c0 pc=0x55a20b56b08a
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00005a7e8 sp=0xc00005a7e0 pc=0x55a20b515761
created by testing.(*T).Run
        /usr/lib/golang/src/testing/testing.go:1487 +0x35f

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0003a2d00, {0x55a20b5c40ed?, 0x55a20b569f45?}, 0x55a20b6686e8)
        /usr/lib/golang/src/testing/testing.go:1488 +0x37a
testing.runTests.func1(0xc0003a2d00?)
        /usr/lib/golang/src/testing/testing.go:1840 +0x6e
testing.tRunner(0xc0003a2d00, 0xc000069cd8)
        /usr/lib/golang/src/testing/testing.go:1440 +0x102
testing.runTests(0xc00011c140?, {0x55a20b72c520, 0xc, 0xc}, {0x7f2a5c568108?, 0x40?, 0x55a20b730ec0?})
        /usr/lib/golang/src/testing/testing.go:1838 +0x457
testing.(*M).Run(0xc00011c140)
        /usr/lib/golang/src/testing/testing.go:1720 +0x5d9
main.main()
        _testmain.go:73 +0x1aa
exit status 2
FAIL    gonum.org/v1/gonum/graph        0.009s
```

It works fine on Go 1.16.
Do you have any idea what might be causing this?

**Comment by sbinet** [comment]
it's `graph` reaching into the guts of the builtin `map` and making assumption about its representation (IIRC).
this was working with Go<1.18 but things have changed.

`gonum@master` has a fix for that:
- https://github.com/gonum/gonum/pull/1729
- https://github.com/gonum/gonum/issues/1728

it just hasn't been yet pushed into a tagged release.

**Comment by kortschak** [comment]
If you can't wait for a release, it can be built with the "safe" tag and it will use reflect instead.
