### ISSUE TITLE
panics and fails in package tests when running with `count` flag.

### ISSUE THREAD

**Issue by soypat** [gonum/gonum#1824]
### What are you trying to do?
Run tests with `go test -count=5 ./...` inside gonum on latest master branch

### What did you expect to happen?
All tests pass.

### What actually happened?

```
~/src/gonum$ time go test -count=5 ./...
?   	gonum.org/v1/gonum	[no test files]
?   	gonum.org/v1/gonum/blas	[no test files]
ok  	gonum.org/v1/gonum/blas/blas32	0.006s
ok  	gonum.org/v1/gonum/blas/blas64	0.025s
ok  	gonum.org/v1/gonum/blas/cblas128	13.900s
ok  	gonum.org/v1/gonum/blas/cblas64	0.007s
ok  	gonum.org/v1/gonum/blas/gonum	15.538s
ok  	gonum.org/v1/gonum/blas/testblas	0.045s
?   	gonum.org/v1/gonum/blas/testblas/benchautogen	[no test files]
ok  	gonum.org/v1/gonum/cmplxs	0.033s
ok  	gonum.org/v1/gonum/cmplxs/cscalar	0.030s
ok  	gonum.org/v1/gonum/diff/fd	0.041s
ok  	gonum.org/v1/gonum/dsp/fourier	266.819s
ok  	gonum.org/v1/gonum/dsp/fourier/internal/fftpack	50.642s
ok  	gonum.org/v1/gonum/dsp/window	0.024s
?   	gonum.org/v1/gonum/dsp/window/cmd/leakage	[no test files]
ok  	gonum.org/v1/gonum/floats	0.053s
ok  	gonum.org/v1/gonum/floats/scalar	0.046s
--- FAIL: TestCopy (0.00s)
panic: simple: node ID collision: 2 [recovered]
	panic: simple: node ID collision: 2

goroutine 35 [running]:
testing.tRunner.func1.2({0x51f7a0, 0xc000440b90})
	/usr/local/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1392 +0x39f
panic({0x51f7a0, 0xc000440b90})
	/usr/local/go/src/runtime/panic.go:838 +0x207
gonum.org/v1/gonum/graph/simple.(*UndirectedGraph).AddNode(0xc00000d920, {0x5781a0, 0x5775c8})
	/home/pato/src/gonum/graph/simple/undirected.go:47 +0x174
gonum.org/v1/gonum/graph.Copy({0x578b60, 0xc00000d920}, {0x578f28, 0xc00000d8f0})
	/home/pato/src/gonum/graph/graph.go:258 +0x6e
gonum.org/v1/gonum/graph_test.TestCopy(0xc00039a1a0)
	/home/pato/src/gonum/graph/graph_test.go:128 +0xdf
testing.tRunner(0xc00039a1a0, 0x552ec8)
	/usr/local/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1486 +0x35f
FAIL	gonum.org/v1/gonum/graph	0.046s
```

and I let it run some and it spewed out enough base64 data to overflow my terminal. 

```
... (continues for lots of lines)
sy779GVMQHBG6k5jDvI5A7/h8gdz+leJXgiJlPotgILcAIkNMmEKuilF2TCY6XlA4HH3cxpixsZpAAuOZggbyywQRaxwUxiAw2oV4DEXKjIllVMiagjvbz8Uxgml3VNi0sdbOjTGdwlqEcYY4Orgs1OjQ6IjOLC4O4/vR37xIkBGnr4GbQvQxGWOmBamrtcW6gkUXvVf3Fuhr09BAgomerO8IUl0k0C8QvDP6yIwxxhhjeslNzJg1xhhjjBkudm6MMcYYMyrs3BhjjDFmVNi5McYYY8yosHNjjDHGmFHx/wIAAP//26nG3JxnKyEAAAAASUVORK5CYII=
    eades_test.go:228: got node positions: map[int64]r2.Vec{0:r2.Vec{X:-1.626271083155058e+22, Y:5.903686807336693e+21}, 1:r2.Vec{X:1.8442322540405892e+23, Y:-6.698729760229611e+22}, 2:r2.Vec{X:-2.1820085261395386e+22, Y:7.926366132126938e+21}, 3:r2.Vec{X:1.3632640829871364e+23, Y:-4.9490471155818e+22}, 4:r2.Vec{X:-9.913379796171175e+23, Y:3.599273844604736e+23}, 5:r2.Vec{X:1.1550893845148759e+23, Y:-4.193332701353889e+22}, 6:r2.Vec{X:1.1550893845148766e+23, Y:-4.193332701354232e+22}, 7:r2.Vec{X:1.1550893845148693e+23, Y:-4.193332701354209e+22}, 8:r2.Vec{X:1.1550893845148647e+23, Y:-4.193332701354535e+22}, 9:r2.Vec{X:1.2331769410067117e+23, Y:-4.477318029382727e+22}, 10:r2.Vec{X:1.2331769410067117e+23, Y:-4.477318029382727e+22}}
FAIL
FAIL	gonum.org/v1/gonum/graph/layout	11.513s
ok  	gonum.org/v1/gonum/graph/multi	3.454s
ok  	gonum.org/v1/gonum/graph/network	0.092s
ok  	gonum.org/v1/gonum/graph/path	71.416s
ok  	gonum.org/v1/gonum/graph/path/dynamic	0.556s
ok  	gonum.org/v1/gonum/graph/path/internal/testgraphs	0.017s
ok  	gonum.org/v1/gonum/graph/product	10.435s
ok  	gonum.org/v1/gonum/graph/set/uid	38.160s
ok  	gonum.org/v1/gonum/graph/simple	1.809s
ok  	gonum.org/v1/gonum/graph/spectral	0.039s
ok  	gonum.org/v1/gonum/graph/testgraph	0.036s
ok  	gonum.org/v1/gonum/graph/topo	1.198s
ok  	gonum.org/v1/gonum/graph/traverse	0.722s
ok  	gonum.org/v1/gonum/integrate	0.496s
ok  	gonum.org/v1/gonum/integrate/quad	0.870s
?   	gonum.org/v1/gonum/integrate/testquad	[no test files]
ok  	gonum.org/v1/gonum/internal/asm/c128	0.054s
ok  	gonum.org/v1/gonum/internal/asm/c64	0.065s
ok  	gonum.org/v1/gonum/internal/asm/f32	0.078s
ok  	gonum.org/v1/gonum/internal/asm/f64	0.287s
ok  	gonum.org/v1/gonum/internal/cmplx64	0.003s
ok  	gonum.org/v1/gonum/internal/math32	0.029s
ok  	gonum.org/v1/gonum/internal/testrand	0.008s
ok  	gonum.org/v1/gonum/interp	0.020s
?   	gonum.org/v1/gonum/lapack	[no test files]
ok  	gonum.org/v1/gonum/lapack/gonum	466.612s
?   	gonum.org/v1/gonum/lapack/lapack64	[no test files]
ok  	gonum.org/v1/gonum/lapack/testlapack	0.051s
ok  	gonum.org/v1/gonum/mat	328.659s
ok  	gonum.org/v1/gonum/mathext	60.957s
ok  	gonum.org/v1/gonum/mathext/internal/amos	53.636s
?   	gonum.org/v1/gonum/mathext/internal/cephes	[no test files]
?   	gonum.org/v1/gonum/mathext/internal/gonum	[no test files]
ok  	gonum.org/v1/gonum/mathext/prng	0.071s
ok  	gonum.org/v1/gonum/num/dual	0.024s
ok  	gonum.org/v1/gonum/num/dualcmplx	0.051s
ok  	gonum.org/v1/gonum/num/dualquat	0.006s
ok  	gonum.org/v1/gonum/num/hyperdual	0.013s
ok  	gonum.org/v1/gonum/num/quat	0.020s
ok  	gonum.org/v1/gonum/optimize	147.554s
ok  	gonum.org/v1/gonum/optimize/convex/lp	351.519s
ok  	gonum.org/v1/gonum/optimize/functions	5.020s
ok  	gonum.org/v1/gonum/spatial/barneshut	530.937s
ok  	gonum.org/v1/gonum/spatial/kdtree	36.896s
?   	gonum.org/v1/gonum/spatial/r1	[no test files]
ok  	gonum.org/v1/gonum/spatial/r2	0.088s
ok  	gonum.org/v1/gonum/spatial/r3	0.057s
ok  	gonum.org/v1/gonum/spatial/vptree	51.064s
ok  	gonum.org/v1/gonum/stat	0.084s
ok  	gonum.org/v1/gonum/stat/card	107.157s
ok  	gonum.org/v1/gonum/stat/combin	0.426s
ok  	gonum.org/v1/gonum/stat/distmat	109.364s
ok  	gonum.org/v1/gonum/stat/distmv	154.774s
ok  	gonum.org/v1/gonum/stat/distuv	205.116s
ok  	gonum.org/v1/gonum/stat/mds	0.042s
--- FAIL: TestImportance (1.82s)
    sample_test.go:205: Covariance matrix mismatch
FAIL
FAIL	gonum.org/v1/gonum/stat/samplemv	46.678s
ok  	gonum.org/v1/gonum/stat/sampleuv	34.924s
ok  	gonum.org/v1/gonum/stat/spatial	3.608s
--- FAIL: TestOperations (0.00s)
    unit_test.go:213: value mismatch for test 0: got=5 want=3
    unit_test.go:213: value mismatch for test 1: got=4 want=2
    unit_test.go:210: dimension mismatch for test 2: got=4 m^2 want=2 m
    unit_test.go:213: value mismatch for test 2: got=4 want=2
    unit_test.go:213: value mismatch for test 3: got=4 want=2
    unit_test.go:210: dimension mismatch for test 4: got=0.25 m^-2 want=0.5 m^-1
    unit_test.go:213: value mismatch for test 4: got=0.25 want=0.5
    unit_test.go:213: value mismatch for test 5: got=0.25 want=0.5
--- FAIL: TestOperations (0.00s)
    unit_test.go:213: value mismatch for test 0: got=7 want=3
    unit_test.go:213: value mismatch for test 1: got=8 want=2
    unit_test.go:210: dimension mismatch for test 2: got=8 m^3 want=2 m
    unit_test.go:213: value mismatch for test 2: got=8 want=2
    unit_test.go:213: value mismatch for test 3: got=8 want=2
    unit_test.go:210: dimension mismatch for test 4: got=0.125 m^-3 want=0.5 m^-1
    unit_test.go:213: value mismatch for test 4: got=0.125 want=0.5
    unit_test.go:213: value mismatch for test 5: got=0.125 want=0.5
--- FAIL: TestOperations (0.00s)
    unit_test.go:213: value mismatch for test 0: got=9 want=3
    unit_test.go:213: value mismatch for test 1: got=16 want=2
    unit_test.go:210: dimension mismatch for test 2: got=16 m^4 want=2 m
    unit_test.go:213: value mismatch for test 2: got=16 want=2
    unit_test.go:213: value mismatch for test 3: got=16 want=2
    unit_test.go:210: dimension mismatch for test 4: got=0.0625 m^-4 want=0.5 m^-1
    unit_test.go:213: value mismatch for test 4: got=0.0625 want=0.5
    unit_test.go:213: value mismatch for test 5: got=0.0625 want=0.5
--- FAIL: TestOperations (0.00s)
    unit_test.go:213: value mismatch for test 0: got=11 want=3
    unit_test.go:213: value mismatch for test 1: got=32 want=2
    unit_test.go:210: dimension mismatch for test 2: got=32 m^5 want=2 m
    unit_test.go:213: value mismatch for test 2: got=32 want=2
    unit_test.go:213: value mismatch for test 3: got=32 want=2
    unit_test.go:210: dimension mismatch for test 4: got=0.03125 m^-5 want=0.5 m^-1
    unit_test.go:213: value mismatch for test 4: got=0.03125 want=0.5
    unit_test.go:213: value mismatch for test 5: got=0.03125 want=0.5
FAIL
FAIL	gonum.org/v1/gonum/unit	0.069s
ok  	gonum.org/v1/gonum/unit/constant	0.037s
FAIL

real	14m28,957s
user	101m43,714s
sys	2m29,247s
```

### What version of Go and Gonum are you using?
```
$ go version
go version go1.18.1 linux/amd64
```

### Does this issue reproduce with the current master?
Yes.

**Comment by kortschak** [comment]
The short answer is that this is not a useful thing to want to do. The slightly longer answer is that this is the result of using package vars for table tests and it doesn't look good. The base64 output is graphic diffs of layout renderings (e.g. https://go.dev/play/p/TpnuCLCtrMV).

**Comment by soypat** [comment]
> not a useful thing to want to do

Yeah, guessed as much. Feel free to close the issue :)

**Comment by kortschak** [comment]
Leave it open. In looking into it, I've found some things I want to fix.
