### ISSUE TITLE
fatal error in internal/asm/f32.AxpyInc

### ISSUE THREAD

**Issue by egonelbre** [gonum/gonum#1923]
### What are you trying to do?

Running benchmarks for a baseline:

```
$ cd internal/asm/f32
$ go test -bench . -count 6 -benchtime 1000x | tee baseline.txt
```

### What actually happened?

```
unexpected fault address 0xc0002a6000
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0xc0002a6000 pc=0x53e4ff]

goroutine 2430 gp=0xc00008b6c0 m=8 mp=0xc000580008 [running]:
runtime.throw({0x582bb0?, 0x43e605?})
        C:/Go.tip/src/runtime/panic.go:1023 +0x65 fp=0xc000135de0 sp=0xc000135db0 pc=0x46a425
runtime.sigpanic()
        C:/Go.tip/src/runtime/signal_windows.go:414 +0xd0 fp=0xc000135e28 sp=0xc000135de0 pc=0x47eeb0
gonum.org/v1/gonum/internal/asm/f32.AxpyInc(0x3f800000, {0xc000180000, 0x186a0, 0x186a0}, {0xc0001e2000, 0x186a0, 0x186a0}, 0x186a0, 0x4, 0x4, ...)
        f:/Code/gonum.org/v1/gonum/internal/asm/f32/axpyinc_amd64.s:42 +0x7f fp=0xc000135e30 sp=0xc000135e28 pc=0x53e4ff
gonum.org/v1/gonum/internal/asm/f32.AxpyInc(0x135ec8?, {0xc000180000?, 0x7?, 0x46f800?}, {0xc0001e2000?, 0xb22ea273cb9c?, 0xc000580008?}, 0xc000135f28?, 0x4634d3?, 0x4a152d?, ...)
        <autogenerated>:1 +0x65 fp=0xc000135ea0 sp=0xc000135e30 pc=0x53f985
gonum.org/v1/gonum/internal/asm/f32.benchaxpyinc(0xc0000b1188, 0x186a0, 0x4, 0x591d58)
        f:/Code/gonum.org/v1/gonum/internal/asm/f32/bench_test.go:108 +0xb1 fp=0xc000135f20 sp=0xc000135ea0 pc=0x53c451
gonum.org/v1/gonum/internal/asm/f32.BenchmarkF32AxpyIncN100000Inc4(0xc0000b1188?)
        f:/Code/gonum.org/v1/gonum/internal/asm/f32/bench_test.go:149 +0x25 fp=0xc000135f50 sp=0xc000135f20 pc=0x53cb45
testing.(*B).runN(0xc0000b1188, 0x1)
        C:/Go.tip/src/testing/benchmark.go:193 +0xf8 fp=0xc000135fa0 sp=0xc000135f50 pc=0x4f2718
testing.(*B).run1.func1()
        C:/Go.tip/src/testing/benchmark.go:215 +0x4e fp=0xc000135fe0 sp=0xc000135fa0 pc=0x4f2d4e
runtime.goexit({})
        C:/Go.tip/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000135fe8 sp=0xc000135fe0 pc=0x49c641
created by testing.(*B).run1 in goroutine 1
        C:/Go.tip/src/testing/benchmark.go:208 +0x90
```

Running with `-race`, I'm getting:

```
BenchmarkF32AxpyIncN100000Inc4-32                       runtime:   gp: gp=0xc00033e1a0, goid=2246, gp->atomicstatus=1412343483
runtime: getg:  g=0xc0000d3380, goid=0,  g->atomicstatus=0
runtime:   gp: gp=0xc00033e9c0, goid=2240, gp->atomicstatus=1412452140
runtime: getg:  g=0xc000504000, goid=0,  g->atomicstatus=0
fatal error: invalid g status
runtime:   gp: gp=0xc00033e680, goid=2080, gp->atomicstatus=1412408004
runtime: getg:  g=0xc000104000, goid=0,  g->atomicstatus=0
runtime:   gp: gp=0xc00033eb60, goid=2256, gp->atomicstatus=1412473858
runtime: getg:  g=0xc000080ea0, goid=0,  g->atomicstatus=0
fatal error: invalid g status
fatal error: invalid g status
fatal error: invalid g status
runtime:   gp: gp=0xc00033e340, goid=2245, gp->atomicstatus=1412366585
runtime: getg:  g=0xc00048a680, goid=0,  g->atomicstatus=0
fatal error: invalid g status

runtime stack:
runtime.throw({0x14024f386?, 0x4840fc90?})
        C:/Program Files/Go/src/runtime/panic.go:1077 +0x65 fp=0x4840fc48 sp=0x4840fc18 pc=0x14003b205
runtime.suspendG(0xc00033e9c0)
        C:/Program Files/Go/src/runtime/preempt.go:134 +0x52a fp=0x4840fcc0 sp=0x4840fc48 pc=0x14003c34a
runtime.markroot.func1()
        C:/Program Files/Go/src/runtime/mgcmark.go:232 +0x89 fp=0x4840fd10 sp=0x4840fcc0 pc=0x14001f609
runtime.markroot(0xc000038b40, 0xbd, 0x1)
        C:/Program Files/Go/src/runtime/mgcmark.go:214 +0x1a8 fp=0x4840fdb8 sp=0x4840fd10 pc=0x14001f2c8
runtime.gcDrain(0xc000038b40, 0x3)
        C:/Program Files/Go/src/runtime/mgcmark.go:1069 +0x37d fp=0x4840fe18 sp=0x4840fdb8 pc=0x14002119d
runtime.gcBgMarkWorker.func2()
        C:/Program Files/Go/src/runtime/mgc.go:1366 +0xa5 fp=0x4840fe68 sp=0x4840fe18 pc=0x14001d985
traceback: unexpected SPWRITE function runtime.systemstack
runtime.systemstack()
        C:/Program Files/Go/src/runtime/asm_amd64.s:509 +0x49 fp=0x4840fe78 sp=0x4840fe68 pc=0x14006c769

...

goroutine 2246 [???, locked to thread]:
fatal error: unexpected signal during runtime execution
panic during panic
[signal 0xc0000005 code=0x0 addr=0x542e9ac3 pc=0x14006157f]

runtime stack:
runtime.throw({0x1402581e2?, 0x3?})
        C:/Program Files/Go/src/runtime/panic.go:1077 +0x65 fp=0x4840f6f8 sp=0x4840f6c8 pc=0x14003b205
runtime.sigpanic()
        C:/Program Files/Go/src/runtime/signal_windows.go:358 +0x265 fp=0x4840f740 sp=0x4840f6f8 pc=0x1400506c5
runtime.traceback1(0xc00033e1a0?, 0x14003cb00?, 0x3?, 0xc00033e1a0, 0x7b?)
        C:/Program Files/Go/src/runtime/traceback.go:845 +0x3f fp=0x4840fa50 sp=0x4840f740 pc=0x14006157f
runtime.traceback(...)
        C:/Program Files/Go/src/runtime/traceback.go:823
runtime.tracebackothers.func1(0xc00033e1a0)
        C:/Program Files/Go/src/runtime/traceback.go:1254 +0xe5 fp=0x4840fa90 sp=0x4840fa50 pc=0x140063085
runtime.forEachGRace(0x4840faf8)
        C:/Program Files/Go/src/runtime/proc.go:621 +0x49 fp=0x4840fac0 sp=0x4840fa90 pc=0x14003e8a9
runtime.tracebackothers(0xc000504000?)
        C:/Program Files/Go/src/runtime/traceback.go:1240 +0xdb fp=0x4840fb28 sp=0x4840fac0 pc=0x140062f7b
runtime.dopanic_m(0xc000504000, 0x14000d413?, 0x1?)
        C:/Program Files/Go/src/runtime/panic.go:1316 +0x231 fp=0x4840fb98 sp=0x4840fb28 pc=0x14003bab1
runtime.fatalthrow.func1()
        C:/Program Files/Go/src/runtime/panic.go:1170 +0x45 fp=0x4840fbd8 sp=0x4840fb98 pc=0x14003b585
runtime.fatalthrow(0x4840fc20?)
        C:/Program Files/Go/src/runtime/panic.go:1163 +0x65 fp=0x4840fc18 sp=0x4840fbd8 pc=0x14003b505
runtime.throw({0x14024f386?, 0x4840fc90?})
        C:/Program Files/Go/src/runtime/panic.go:1077 +0x65 fp=0x4840fc48 sp=0x4840fc18 pc=0x14003b205
runtime.suspendG(0xc00033e9c0)
        C:/Program Files/Go/src/runtime/preempt.go:134 +0x52a fp=0x4840fcc0 sp=0x4840fc48 pc=0x14003c34a
runtime.markroot.func1()
        C:/Program Files/Go/src/runtime/mgcmark.go:232 +0x89 fp=0x4840fd10 sp=0x4840fcc0 pc=0x14001f609
runtime.markroot(0xc000038b40, 0xbd, 0x1)
        C:/Program Files/Go/src/runtime/mgcmark.go:214 +0x1a8 fp=0x4840fdb8 sp=0x4840fd10 pc=0x14001f2c8
runtime.gcDrain(0xc000038b40, 0x3)
        C:/Program Files/Go/src/runtime/mgcmark.go:1069 +0x37d fp=0x4840fe18 sp=0x4840fdb8 pc=0x14002119d
runtime.gcBgMarkWorker.func2()
        C:/Program Files/Go/src/runtime/mgc.go:1366 +0xa5 fp=0x4840fe68 sp=0x4840fe18 pc=0x14001d985
traceback: unexpected SPWRITE function runtime.systemstack
runtime.systemstack()
        C:/Program Files/Go/src/runtime/asm_amd64.s:509 +0x49 fp=0x4840fe78 sp=0x4840fe68 pc=0x14006c769
```

### What version of Go and Gonum are you using?

```
$ go version
go version go1.21.3 windows/amd64
$ git rev-parse HEAD
fa306f215a0186dfb3c1cad95190d7c9a249eb15
```

### Does this issue reproduce with the current master?

Yes.

**Comment by egonelbre** [comment]
Fix was merged.
