### ISSUE TITLE
Gonum is ~an order of magnitude slower than Numpy?

### ISSUE THREAD

**Issue by rossamurphy** [gonum/gonum#2008]
### What are you trying to do?
Run a very simple script to compute eigenvalues and singular value decomposition of arbitrary sized (large-ish) matrices, filled with random numbers drawn from the uniform distribution.

### What did you do?

```go
package main

import (
	"fmt"
	"math/rand"

	"time"

	"gonum.org/v1/gonum/lapack/lapack64"
	"gonum.org/v1/gonum/mat"
	"gonum.org/v1/netlib/lapack/netlib"
)

func init() {
	lapack64.Use(netlib.Implementation{})
}

func main() {
	t1 := time.Now()
	data := make([]float64, 2000*2000)
	for i := range data {
		data[i] = rand.NormFloat64()
	}
	t2 := time.Now()
	a := mat.NewDense(2000, 2000, data)
	t3 := time.Now()
	a.Mul(a.T(), a)
	t4 := time.Now()
	var eigen mat.Eigen
	eigen.Factorize(a, mat.EigenNone)

	t5 := time.Now()
	svd := new(mat.SVD)

	svd.Factorize(a, mat.SVDNone)
	t6 := time.Now()

	fmt.Println("Total time taken:", time.Since(t1))
	fmt.Println("Time taken to generate data:", t2.Sub(t1))
	fmt.Println("Time taken to create matrix:", t3.Sub(t2))
	fmt.Println("Time taken to multiply matrix:", t4.Sub(t3))
	fmt.Println("Time taken to calculate eigenvalues:", t5.Sub(t4))
	fmt.Println("Time taken to calculate svd:", t6.Sub(t5))
}
```

I ran this script after following the issue (and helpful instructions found in [this issue](https://github.com/gonum/gonum/issues/511)).

That is to say, I did:

```zsh
  go get -d gonum.org/v1/netlib/...
```

Followed by

```zsh
git clone https://github.com/xianyi/OpenBLAS
  cd OpenBLAS
  sudo make
  sudo make install
```

Followed by 

```zsh
  CGO_LDFLAGS="-L/GitHub/OpenBLAS -lopenblas" go install gonum.org/v1/netlib/lapack/netlib
```

Followed by 
```zsh
export LD_LIBRARY_PATH=/GitHub/OpenBLAS/lib/
```

and then did

```zsh
CGO_ENABLED=1 go build .
```

and then ran the produced binary.

### What did you expect to happen?
I expected to see performance _vaguely_ similar to a very vanilla version of the same logic in Python.

i.e. I expected this:

❯ go run .
Total time taken: 15.664191709s
Time taken to generate data: 57.784292ms
Time taken to create matrix: 12.375µs
Time taken to multiply matrix: 399.226083ms
Time taken to calculate eigenvalues: 7.596843625s
Time taken to calculate svd: 7.6103055s

to be vaguely similar in performance to a Python implementation.

### What actually happened?

The Python implementation was almost an order of magnitude faster in all operations:

❯ python play.py
Total time: 2925.4 miliseconds
Matrix creation: 23.3 miliseconds
Matrix multiplication: 23.8 miliseconds
Eigenval calculation: 1298.2 miliseconds
SVD calculation: 1580.1 miliseconds
Cholesky decomposition: 27.9 miliseconds

I was surprised by this, as both are using blas backends. 

### What version of Go and Gonum are you using?
go version go1.23.4 darwin/arm64
gonum.org/v1/gonum v0.15.2-0.20241213195509-ca6b5f46d40a

### Does this issue reproduce with the current master?

yes.

for reference, the Python script:

```python
import numpy as np
import time


t1 = time.time()
a = np.random.rand(2_000, 2_000)
a.shape
# print(a)
t2 = time.time()
b = a.T @ a
t3 = time.time()
# calculate the svd of b
result = np.linalg.eigvals(b)
# print(result)
t4 = time.time()
t5 = time.time()
result = np.linalg.svd(b)
t6 = time.time()
# cholesky decomp
result = np.linalg.cholesky(b)
t7 = time.time()
# np.show_config()
print(f"Total time: {(t6 - t1)*1e3:.1f} miliseconds")
print(f"Matrix creation: {(t2 - t1)*1e3:.1f} miliseconds")
print(f"Matrix multiplication: {(t3 - t2)*1e3:.1f} miliseconds")
print(f"Eigenval calculation: {(t4 - t3)*1e3:.1f} miliseconds")
print(f"SVD calculation: {(t6 - t5)*1e3:.1f} miliseconds")
print(f"Cholesky decomposition: {(t7 - t6)*1e3:.1f} miliseconds")
```

**Comment by kortschak** [comment]
The multiplication is using the native implementation, so add `blas64.Use(netlib.Implementation{})`. The `b` matrix is symmetric, so for the ED, you should be using `mat.EigenSym`.

This doesn't explain all of the time, but may improve parts. Doing benchmarking and profilling to see where the time is going would be helpful.

**Comment by rossamurphy** [comment]
Thanks for coming back to me on this!

I can't add the import you mention:

❯ go run .
# gopherit
./main.go:16:13: cannot use netlib.Implementation{} (value of type netlib.Implementation) as blas.Float64 value in argument to blas64.Use: netlib.Implementation does not implement blas.Float64 (missing method Dasum)

If you could please direct me to where I'm going wrong, I can make the changes, and come back with the results of the profiler.

thanks a lot

**Comment by rossamurphy** [comment]
<img width="935" alt="image" src="https://github.com/user-attachments/assets/7658fa5a-0c03-4187-a414-39830d65ba61" />
The same error, highlighted by the linter

**Comment by kortschak** [comment]
You don't show the import in your image, but I suspect you are using the lapack implementation. Use https://pkg.go.dev/gonum.org/v1/netlib/blas/netlib (this will require an import rename).

**Comment by rossamurphy** [comment]
Thanks a lot Dan. I did that. 

```go
package main

import (
	"fmt"
	"gonum.org/v1/gonum/blas/blas64"

	"gonum.org/v1/gonum/lapack/lapack64"
	"math/rand"

	"time"

	"gonum.org/v1/gonum/mat"
	blasnetlib "gonum.org/v1/netlib/blas/netlib"
	lapacknetlib "gonum.org/v1/netlib/lapack/netlib"
)

func init() {
	blas64.Use(blasnetlib.Implementation{})
	lapack64.Use(lapacknetlib.Implementation{})
}
```

I'm afraid I'm still running into even weirder behaviour now (below).

Not to worry. I suspect this might be something more nuanced my side.. as now it looks like we're delving into annoying C linker issues.. I've managed to implement what I needed to implement in a different library, so, no stress on this, I don't want to take up more of your time.

The full error stack if you are interested:



❯ go build
# gonum.org/v1/netlib/blas/netlib
cgo-gcc-prolog:48:3: error: unknown type name 'blasint'
cgo-gcc-prolog:52:3: error: unknown type name 'blasint'
cgo-gcc-prolog:55:3: error: unknown type name 'blasint'
cgo-gcc-prolog:68:3: error: unknown type name 'blasint'
cgo-gcc-prolog:71:3: error: unknown type name 'blasint'
cgo-gcc-prolog:74:3: error: unknown type name 'blasint'
cgo-gcc-prolog:87:3: error: unknown type name 'blasint'
cgo-gcc-prolog:90:3: error: unknown type name 'blasint'
cgo-gcc-prolog:93:3: error: unknown type name 'blasint'
cgo-gcc-prolog:107:3: error: unknown type name 'blasint'
cgo-gcc-prolog:110:3: error: unknown type name 'blasint'
cgo-gcc-prolog:113:3: error: unknown type name 'blasint'
cgo-gcc-prolog:129:3: error: unknown type name 'blasint'
cgo-gcc-prolog:130:3: error: unknown type name 'blasint'
cgo-gcc-prolog:131:3: error: unknown type name 'blasint'
cgo-gcc-prolog:132:3: error: unknown type name 'blasint'
cgo-gcc-prolog:135:3: error: unknown type name 'blasint'
cgo-gcc-prolog:138:3: error: unknown type name 'blasint'
cgo-gcc-prolog:142:3: error: unknown type name 'blasint'
fatal error: too many errors emitted, stopping now [-ferror-limit=]
# gonum.org/v1/netlib/lapack/lapacke
cgo-gcc-prolog:1471:178: error: incompatible pointer to integer conversion passing 'int32_t *' (aka 'int *') to parameter of type 'int'; dereference with * [-Wint-conversion]
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:5778:71: note: passing argument to parameter 'ns' here
cgo-gcc-prolog:3243:105: error: too many arguments to function call, expected 6, have 7
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:10477:12: note: 'LAPACKE_cheswapr_work' declared here
cgo-gcc-prolog:6540:105: error: too many arguments to function call, expected 6, have 7
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:10513:12: note: 'LAPACKE_csyswapr_work' declared here
cgo-gcc-prolog:8019:168: warning: incompatible pointer types passing 'float *' to parameter of type '_Complex float *' [-Wincompatible-pointer-types]
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:10600:55: note: passing argument to parameter 'theta' here
cgo-gcc-prolog:8799:165: error: incompatible pointer to integer conversion passing 'int32_t *' (aka 'int *') to parameter of type 'int'; dereference with * [-Wint-conversion]
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:4749:71: note: passing argument to parameter 'ns' here
cgo-gcc-prolog:10156:178: error: incompatible pointer to integer conversion passing 'int32_t *' (aka 'int *') to parameter of type 'int'; dereference with * [-Wint-conversion]
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:5771:71: note: passing argument to parameter 'ns' here
cgo-gcc-prolog:15521:105: error: too many arguments to function call, expected 6, have 7
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:10678:12: note: 'LAPACKE_dsyswapr_work' declared here
cgo-gcc-prolog:15613:104: warning: incompatible pointer types passing 'double *' to parameter of type '_Complex double *' [-Wincompatible-pointer-types]
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:10685:57: note: passing argument to parameter 'work' here
cgo-gcc-prolog:17106:165: error: incompatible pointer to integer conversion passing 'int32_t *' (aka 'int *') to parameter of type 'int'; dereference with * [-Wint-conversion]
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:4743:71: note: passing argument to parameter 'ns' here
cgo-gcc-prolog:18466:178: error: incompatible pointer to integer conversion passing 'int32_t *' (aka 'int *') to parameter of type 'int'; dereference with * [-Wint-conversion]
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:5764:71: note: passing argument to parameter 'ns' here
cgo-gcc-prolog:23774:105: error: too many arguments to function call, expected 6, have 7
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:10771:12: note: 'LAPACKE_ssyswapr_work' declared here
cgo-gcc-prolog:23866:104: warning: incompatible pointer types passing 'float *' to parameter of type '_Complex float *' [-Wincompatible-pointer-types]
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:10778:56: note: passing argument to parameter 'work' here
cgo-gcc-prolog:26698:178: error: incompatible pointer to integer conversion passing 'int32_t *' (aka 'int *') to parameter of type 'int'; dereference with * [-Wint-conversion]
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:5786:71: note: passing argument to parameter 'ns' here
cgo-gcc-prolog:28473:105: error: too many arguments to function call, expected 6, have 7
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:10818:12: note: 'LAPACKE_zheswapr_work' declared here
cgo-gcc-prolog:31760:105: error: too many arguments to function call, expected 6, have 7
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:10854:12: note: 'LAPACKE_zsyswapr_work' declared here
cgo-gcc-prolog:33239:168: warning: incompatible pointer types passing 'double *' to parameter of type '_Complex double *' [-Wincompatible-pointer-types]
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:10941:56: note: passing argument to parameter 'theta' here

**Comment by kortschak** [comment]
Even without this, it would be helpful to do some profiling on where the time is going.

**Comment by rossamurphy** [comment]
Hey Dan, sorry this took a couple days.

I reinstalled openblas + pkg-config + gfortran in an effort to figure out this error, and ended up making the problem worse.. Now, neither of the bindings (either to blas or lapack) are working.

Info below:

1. The above errors now happen any time I try to use the netlib bindings to blas or lapack.
2. Moreover, they'll be thrown any time I try to install the bindings. 
3. This happens regardless of whether I try to install with the linker flags to my homebrew installed blas (living at /opt/homebrew/opt/openblas/...), or, to the locally made blas (living at /opt/OpenBlas/...).
4. i.e. 
```zsh
CGO_LDFLAGS="/opt/homebrew/opt/openblas/ -lopenblas" go install gonum.org/v1/netlib/lapack/netlib  
```
will fail, 
and, similiarly:
```zsh
CGO_LDFLAGS="/opt/OpenBlas/ -lopenblas" go install gonum.org/v1/netlib/lapack/netlib                  
```
will also fail.
5. Point 4 will fail with this:
# gonum.org/v1/netlib/lapack/lapacke
cgo-gcc-prolog:1471:178: error: incompatible pointer to integer conversion passing 'int32_t *' (aka 'int *') to parameter of type 'int'; dereference with * [-Wint-conversion]
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:5778:71: note: passing argument to parameter 'ns' here
cgo-gcc-prolog:3243:105: error: too many arguments to function call, expected 6, have 7
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:10477:12: note: 'LAPACKE_cheswapr_work' declared here
cgo-gcc-prolog:6540:105: error: too many arguments to function call, expected 6, have 7
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:10513:12: note: 'LAPACKE_csyswapr_work' declared here
cgo-gcc-prolog:8019:168: warning: incompatible pointer types passing 'float *' to parameter of type '_Complex float *' [-Wincompatible-pointer-types]
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:10600:55: note: passing argument to parameter 'theta' here
cgo-gcc-prolog:8799:165: error: incompatible pointer to integer conversion passing 'int32_t *' (aka 'int *') to parameter of type 'int'; dereference with * [-Wint-conversion]
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:4749:71: note: passing argument to parameter 'ns' here
cgo-gcc-prolog:10156:178: error: incompatible pointer to integer conversion passing 'int32_t *' (aka 'int *') to parameter of type 'int'; dereference with * [-Wint-conversion]
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:5771:71: note: passing argument to parameter 'ns' here
cgo-gcc-prolog:15521:105: error: too many arguments to function call, expected 6, have 7
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:10678:12: note: 'LAPACKE_dsyswapr_work' declared here
cgo-gcc-prolog:15613:104: warning: incompatible pointer types passing 'double *' to parameter of type '_Complex double *' [-Wincompatible-pointer-types]
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:10685:57: note: passing argument to parameter 'work' here
cgo-gcc-prolog:17106:165: error: incompatible pointer to integer conversion passing 'int32_t *' (aka 'int *') to parameter of type 'int'; dereference with * [-Wint-conversion]
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:4743:71: note: passing argument to parameter 'ns' here
cgo-gcc-prolog:18466:178: error: incompatible pointer to integer conversion passing 'int32_t *' (aka 'int *') to parameter of type 'int'; dereference with * [-Wint-conversion]
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:5764:71: note: passing argument to parameter 'ns' here
cgo-gcc-prolog:23774:105: error: too many arguments to function call, expected 6, have 7
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:10771:12: note: 'LAPACKE_ssyswapr_work' declared here
cgo-gcc-prolog:23866:104: warning: incompatible pointer types passing 'float *' to parameter of type '_Complex float *' [-Wincompatible-pointer-types]
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:10778:56: note: passing argument to parameter 'work' here
cgo-gcc-prolog:26698:178: error: incompatible pointer to integer conversion passing 'int32_t *' (aka 'int *') to parameter of type 'int'; dereference with * [-Wint-conversion]
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:5786:71: note: passing argument to parameter 'ns' here
cgo-gcc-prolog:28473:105: error: too many arguments to function call, expected 6, have 7
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:10818:12: note: 'LAPACKE_zheswapr_work' declared here
cgo-gcc-prolog:31760:105: error: too many arguments to function call, expected 6, have 7
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:10854:12: note: 'LAPACKE_zsyswapr_work' declared here
cgo-gcc-prolog:33239:168: warning: incompatible pointer types passing 'double *' to parameter of type '_Complex double *' [-Wincompatible-pointer-types]
../../go/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/lapacke/lapacke.h:10941:56: note: passing argument to parameter 'theta' here
6. If I try a similar operation for blas, i.e. 
```zsh
CGO_LDFLAGS="/opt/OpenBlas/ -lopenblas" go install gonum.org/v1/netlib/blas/netlib
```
I will get:
# gonum.org/v1/netlib/blas/netlib
cgo-gcc-prolog:48:3: error: unknown type name 'blasint'
cgo-gcc-prolog:52:3: error: unknown type name 'blasint'
cgo-gcc-prolog:55:3: error: unknown type name 'blasint'
cgo-gcc-prolog:68:3: error: unknown type name 'blasint'
cgo-gcc-prolog:71:3: error: unknown type name 'blasint'
cgo-gcc-prolog:74:3: error: unknown type name 'blasint'
cgo-gcc-prolog:87:3: error: unknown type name 'blasint'
cgo-gcc-prolog:90:3: error: unknown type name 'blasint'
cgo-gcc-prolog:93:3: error: unknown type name 'blasint'
cgo-gcc-prolog:107:3: error: unknown type name 'blasint'
cgo-gcc-prolog:110:3: error: unknown type name 'blasint'
cgo-gcc-prolog:113:3: error: unknown type name 'blasint'
cgo-gcc-prolog:129:3: error: unknown type name 'blasint'
cgo-gcc-prolog:130:3: error: unknown type name 'blasint'
cgo-gcc-prolog:131:3: error: unknown type name 'blasint'
cgo-gcc-prolog:132:3: error: unknown type name 'blasint'
cgo-gcc-prolog:135:3: error: unknown type name 'blasint'
cgo-gcc-prolog:138:3: error: unknown type name 'blasint'
cgo-gcc-prolog:142:3: error: unknown type name 'blasint'
fatal error: too many errors emitted, stopping now [-ferror-limit=]
7. So, the errors which I see when I try to run / build my code are coming from the netlib bindings failing to install when linked against OpenBlas on my system.
8. Brew OpenBlas was installed simply by ```zsh brew install openblas```.  The other OpenBlas was installed by:
```zsh
git clone https://github.com/xianyi/OpenBLAS
  cd OpenBLAS
  sudo make
  sudo make install
```
9. My machine is an arm64 m1.
10. Nonetheless, in case helpful, I've prepared some profiling reports for running a version of my script (modified, but with all the main parts) using the native gonum implementation. I'll email the profile report (cpu.prof) to you now (I can't attach the profiler report to a GitHub issue message). You can choose either to run the web ui and inspect the report by
```zsh
go tool pprof -http=:8080 tests.test cpu.prof
```
Or, if easier, I'll also include a screenshot of the top level flame graph:
<img width="1581" alt="image" src="https://github.com/user-attachments/assets/04beb9ce-c90a-455f-ab17-89c23d5db47c" />

Cheers for your help on this

**Comment by kortschak** [comment]
With
```
package tests

import (
	"math/rand"
	"testing"

	"gonum.org/v1/gonum/blas/blas64"
	"gonum.org/v1/gonum/lapack/lapack64"
	"gonum.org/v1/gonum/mat"
	netlib_blas "gonum.org/v1/netlib/blas/netlib"
	netlib_lapack "gonum.org/v1/netlib/lapack/netlib"
)

func BenchmarkMatrixOperations(b *testing.B) {
	blas64.Use(netlib_blas.Implementation{})
	lapack64.Use(netlib_lapack.Implementation{})
	data := make([]float64, 2000*2000)

	for i := 0; i < b.N; i++ {
		b.StopTimer()
		for i := range data {
			data[i] = rand.Float64()
		}
		b.StartTimer()

		a := mat.NewDense(2000, 2000, data)
		a.Mul(a.T(), a)

		var eigen mat.Eigen
		eigen.Factorize(a, mat.EigenNone)

		svd := new(mat.SVD)
		svd.Factorize(a, mat.SVDNone)
	}
}
```
and an old OpenBLAS (I run an ancient machine, and cannot get the tip of develop v0.3.28 to pass tests in the repo, but the gonum netlib tests pass, so I suspect this is just the OpenBLAS build chain exceeding what I have available).

I see
```
$ CGO_LDFLAGS="-L…/OpenBLAS -lopenblas" go test -bench . -v
goos: linux
goarch: amd64
pkg: netlib
cpu: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
BenchmarkMatrixOperations
Wrong parameter 12 in LAPACKE_dgesvd_work
panic: lapack: insufficient declared workspace length

goroutine 34 [running]:
gonum.org/v1/netlib/lapack/netlib.Implementation.Dgesvd({}, 0xa8?, 0xd1?, 0x18?, 0x4a5108?, {0xc005fa4000?, 0x18?, 0x2000005?}, 0xc000075b38?, {0xc0000b8000, ...}, ...)
	…/pkg/mod/gonum.org/v1/netlib@v0.0.0-20230729102104-8b8060e7531f/lapack/netlib/lapack.go:2019 +0x44f
gonum.org/v1/gonum/lapack/lapack64.Gesvd(0x4e, 0x4e, {0x7d0, 0x7d0, {0xc005fa4000, 0x3d0900, 0x3d0900}, 0x7d0}, {0x0, 0x0, ...}, ...)
	…/pkg/mod/gonum.org/v1/gonum@v0.15.1/lapack/lapack64/lapack64.go:354 +0x1d0
gonum.org/v1/gonum/mat.(*SVD).Factorize(0xc000075eb0, {0x65aeb8, 0xc00012c900}, 0x0)
	…/pkg/mod/gonum.org/v1/gonum@v0.15.1/mat/svd.go:139 +0x8f4
netlib.BenchmarkMatrixOperations(0xc000152508)
	…/thinking/netlib/main_test.go:33 +0x18e
testing.(*B).runN(0xc000152508, 0x1)
	…/src/testing/benchmark.go:193 +0xf0
testing.(*B).run1.func1()
	…/src/testing/benchmark.go:215 +0x48
created by testing.(*B).run1 in goroutine 1
	…/src/testing/benchmark.go:208 +0x90
exit status 2
FAIL	netlib	7.198s
```
Given that
```
package tests

import (
	"math/rand"
	"testing"

	"gonum.org/v1/gonum/mat"
)

func BenchmarkMatrixOperations(b *testing.B) {
	data := make([]float64, 2000*2000)

	for i := 0; i < b.N; i++ {
		b.StopTimer()
		for i := range data {
			data[i] = rand.Float64()
		}
		b.StartTimer()

		a := mat.NewDense(2000, 2000, data)
		a.Mul(a.T(), a)

		var eigen mat.Eigen
		eigen.Factorize(a, mat.EigenNone)

		svd := new(mat.SVD)
		svd.Factorize(a, mat.SVDNone)
	}
}
```
using the Gonum implementation works, and previous experience with issues in this part of the world, my suspicion is that there is a bug in the Netlib implementation (though I have no firm evidence to back up this claim). From an shallow look, it appears that `lvt` is being checked despite `vt` not being used since we are calling with `SVDNone`. This is confirmed by changing the SVD call to `svd.Factorize(a, mat.SVDFull)` which then passes
```
 CGO_LDFLAGS="-L…/OpenBLAS -lopenblas" go test -bench . -v
goos: linux
goarch: amd64
pkg: netlib
cpu: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
BenchmarkMatrixOperations
BenchmarkMatrixOperations-8   	       1	55609257041 ns/op
PASS
ok  	netlib	55.751s
```
since in that case our code correctly sets the required lengths. I think this is a bug in OpenBLAS.

**Comment by rossamurphy** [comment]
Hi Dan,

Thanks so much for taking the time to thoroughly go through this, especially testing it on various machines. I really appreciate the effort.

That's an annoying bug. Would you recommend me raising it with the OpenBlas team? Also, could you recommend any other way I could achieve similar speeds to Numpy when it comes to vector operations in Go? 

For context: I, basically, would like to be able to have similar speeds/performance of doing matrix operations, in a language that doesn't suffer from all the pitfalls Python does. I'd be up for using a combination of Go and Python, if Go to Python FFI was more mature, but I can't really see anything that rivals Pyo3 on the Rust side. Ideally I could just do everything in Go, but, I can't really pay the performance penalty for such a critical feature of the product.

thanks

**Comment by kortschak** [comment]
I will file an issue with OpenBLAS.

Sorry, I can't give any advice.

**Comment by kortschak** [comment]
@rossamurphy The OpenBLAS issue has been fixed.

**Comment by rossamurphy** [comment]
Thanks a mil for letting me know, Dan. I'll try it again in the AM 🙏🏼
