### ISSUE TITLE
lapack/gonum: coverage of Dgesvd is insufficient

### ISSUE THREAD

**Issue by vladimir-ch** [gonum/gonum#816]
Based on the recently found issues with ldwork I tried to modify DgesvdTest to include also minimum and medium workspace lengths. I get the following panic which is in code not currently covered by the test:
```
panic: lapack: tau has insufficient length [recovered]
	panic: lapack: tau has insufficient length

goroutine 18 [running]:
testing.tRunner.func1(0xc0000c2100)
	/usr/lib/go/src/testing/testing.go:792 +0x387
panic(0x678ce0, 0x72f0b0)
	/usr/lib/go/src/runtime/panic.go:513 +0x1b9
gonum.org/v1/gonum/lapack/gonum.Implementation.Dormqr(0x4e52, 0x9, 0x5, 0x5, 0xc0000e5450, 0x19, 0x19, 0x5, 0xc0000e5618, 0x14, ...)
	/home/chalupecky/src/gonum.org/v1/gonum/lapack/gonum/dormqr.go:67 +0x16e5
gonum.org/v1/gonum/lapack/gonum.Implementation.Dormbr(0x4e5251, 0x9, 0x5, 0x5, 0xc0000e5450, 0x19, 0x19, 0x5, 0xc0000e5618, 0x14, ...)
	/home/chalupecky/src/gonum.org/v1/gonum/lapack/gonum/dormbr.go:118 +0x58d
gonum.org/v1/gonum/lapack/gonum.Implementation.Dgesvd(0xc000064141, 0x9, 0x5, 0xc000122000, 0x2d, 0x2d, 0x5, 0xc00007a7e0, 0x5, 0x5, ...)
	/home/chalupecky/src/gonum.org/v1/gonum/lapack/gonum/dgesvd.go:788 +0x3bd1
gonum.org/v1/gonum/lapack/testlapack.DgesvdTest(0xc0000c2100, 0x731860, 0x94a7a8)
```
It happens when lwork is the documented minimum.

**Comment by kortschak** [comment]
Do you see the same issue when running the test for the col-major implementation.

**Comment by vladimir-ch** [comment]
Partially false alarm. The crash happened only for zero sized test matrix. For the minimum size the fault was mine, the test code didn't allocate the work slice. After fixing it still crashes for zero size because the optimum lwork is returned as 0 by Dgesvd. So it's nothing serious but should be fixed anyway. I'll take a look tomorrow.

**Comment by vladimir-ch** [comment]
My previous comment applies when testing netlib lapack. I don't see in the fortran code why the reference returns zero optimum worksize for zero size matrices, it should always return at least 1.

Our implementation crashes with minimum workspace size already for 1x1 matrix, for non-optimum workspace size also for larger size (for example I get a crash for 300x100 but it will most likely depend on the workspace size).
